config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments
    resources :likes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
  validates :email, uniqueness: true

  validates :password, :password_confirmation, presence: true, on: :create
  validates :password, confirmation: true

  has_many :posts
  has_many :comments
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_active_admin_user!
    authenticate_user!
    unless current_user.superadmin?
      flash[:alert] = "Unauthorized Access!"
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    @post = find_post
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user

    if @comment.save!
      flash[:success] = 'Comment created successfully'
    else
      flash[:error] = 'Failed to create comment'
    end
    redirect_to @post
  end

  def destroy
    @post = find_post
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to action: 'show'
  end

  private

  def find_post
    Post::Getter.new(params[:post_id]).call
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    @post = find_post
    @like = @post.likes.create(user: current_user)

    if @like.save!
      flash[:success] = 'Liked'
    else
      flash[:error] = 'Error'
    end

    redirect_to @post
  end

  def destroy
    @post = find_post
    @like = @post.likes.find(params[:id])
    @like.destroy
    redirect_to @post
  end

  private

  def find_post
    Post::Getter.new(params[:post_id]).call
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @posts = Post::Index.new.call
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))

    if @post.save!
      flash[:success] = 'Post created successfully'
      redirect_to @post
    else
      render :new
    end
  end

  def show
    @post = find_post
  end

  def edit
    @post = find_post
    owner?
  end

  def update
    @post = find_post
    owner?

    if @post.update(post_params)
      flash[:success] = 'Post updated successfully'
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = find_post
    owner?
    @post.destroy
    flash[:success] = 'Post deleted successfully'
    redirect_to action: 'index'
  end

  private

  def find_post
    Post::Getter.new(params[:id]).call
  end

  def owner?
    unless current_user == @post.user
      redirect_back fallback_location: root_path
      flash[:alert] = 'User is not owner'
    end
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment_listing.html.slim
table
  thead
    tr
      th User
      th Comment

  tbody
    - @post.comments.each do |comment|
      tr
        td = comment.user_id
        td = comment.content

br

app/views/comments/_form.html.slim
h2 Add a comment

= simple_form_for([@post, @post.comments.build]) do |f|
  .form-inputs
    = f.text_area :content
  .form-actions
    = f.button :submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.slim
p
  = (@post.likes.count) == 1 ? "Like: " : "Likes: "
  = @post.likes.count

- pre_like = @post.likes.find { |like| like.user_id == current_user.id }
- if pre_like
    => button_to 'Unlike', post_like_path(@post, pre_like), method: :delete
- else
    => button_to 'Like', post_likes_path(@post), method: :post

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|

  .form-inputs
    = f.input :title

    = f.label :content
    br
    = f.text_area :content

  .form-actions
    = f.button :submit

app/views/posts/_user_state.html.slim
- if current_user
    => button_to 'Logout', destroy_user_session_path, method: :delete
- else
    => link_to 'Register', new_user_registration_path
    br
    =< button_to 'Login', new_user_session_path, method: :get

app/views/posts/edit.html.slim
h1 Editing Post

== render 'form'

=> link_to 'Show', @post
'|
=< link_to 'Back', posts_url

app/views/posts/index.html.slim
h1 All Posts

== render 'user_state'
- flash.each do |type, message|
      .flash
        = message

- if current_user
  - if current_user.superadmin?
      => link_to 'Admin Panel', admin_root_path

table
  thead
    tr
      th Title
      th Content
      th Likes
      th Comments
      th Show
      th Edit
      th Delete

  tbody
    - @posts.each do |post|
      tr
        td = post.title
        td = post.content
        td = post.likes.count
        td = post.comments.count
        td = link_to 'Show', post
        - if current_user
          - if current_user.id == post.user_id
              td = link_to 'Edit', edit_post_path(post)
              td = button_to 'Delete', post, method: :delete

br

=> link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1 New Post

== render 'form'

= link_to 'Back', posts_url

app/views/posts/show.html.slim
- flash.each do |type, message|
      .flash
        = message

p
  strong Title:
  = @post.title

p
  strong Content:
  = @post.content

=> link_to 'Edit', edit_post_path(@post)
'|
=< link_to 'Back', posts_path

- if current_user
   == render 'comments/form'
   == render 'likes/like'
br
== render 'comments/comment_listing'